from django.db import models
from django.utils.timezone import now

class Document(models.Model):
    """
    Represents a document stored in the vector store.
    """
    title = models.CharField(max_length=255)
    content = models.TextField()
    embedding_id = models.CharField(max_length=255, unique=True, null=True, blank=True)  # ID in vector store
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Query(models.Model):
    """
    Represents a user query sent to the RAG system.
    """
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:50]  # Display the first 50 characters


class Response(models.Model):
    """
    Represents a response generated by the system for a query.
    """
    query = models.ForeignKey(Query, on_delete=models.CASCADE, related_name="responses")
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Response to Query {self.query.id}"


class RetrievalLog(models.Model):
    """
    Logs document retrievals for queries.
    """
    query = models.ForeignKey(Query, on_delete=models.CASCADE, related_name="retrieval_logs")
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name="retrieval_logs")
    score = models.FloatField()  # Relevance score from the vector store
    retrieved_at = models.DateTimeField(default=now)

    def __str__(self):
        return f"Log for Query {self.query.id} - Document {self.document.id}"

# Create your models here.
