services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/pantheon-sales-c051b0d6af5f.json
      - DEBUG=1
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./secrets:/secrets:ro
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pantheor_user
      POSTGRES_PASSWORD: pantheor_password
      POSTGRES_DB: pantheor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
